version: '3'

services:

  db:
    image: postgres:latest
    container_name: db_app
    hostname: postgres
    user: postgres
    ports:
      - 5432:5432
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis_app
    hostname: redis
    ports:
      - 6379:6379
    env_file:
      - .env

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    command:
      - sh
      - -c
      - |
        alembic upgrade head
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8787:8000
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app

  celery:
    build:
      context: .
    container_name: celery_app
    command: celery -A document.tasks:celery worker --loglevel=INFO
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./:/app

  flower:
    build:
      context: .
    command: celery -A document.tasks:celery flower
    ports:
      - 5555:5555
    env_file:
      - .env
    depends_on:
      - redis
      - celery
    volumes:
      - ./:/ap